const path = require('path');
const express = require('express');
const Userrouter = express.Router();
const rootdir = require('../utils/pathUtil');
const homecontroller = require('../controller/home');
Userrouter.get("/",homecontroller.getLogin);
Userrouter.get("/home",homecontroller.getHome);
Userrouter.get("/Login",homecontroller.getLogin);
Userrouter.post("/logout",homecontroller.postLogout);
Userrouter.get("/home/form",homecontroller.getForm);
Userrouter.get("/postjob",homecontroller.getPostjob);
Userrouter.get("/help-support", homecontroller.gethelp);
Userrouter.get("/about-us" , homecontroller.getAbout);
Userrouter.get("/contact" , homecontroller.getContact);
Userrouter.get("/chat",homecontroller.getChat);
Userrouter.post("/chat", homecontroller.postChat);
Userrouter.post("/applicant/hire", homecontroller.postApplicantHire);
// Userrouter.get("/profile", homecontroller.getProfile);
// Userrouter.get("/settings", homecontroller.getSettings);
exports.Userrouter = Userrouter;
